version: "3.8"

services:
  app:
    restart: always
    build:
      context: .
      args:
        - WITH_COMPOSER=true
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/sites-enabled
      
# Uncomment 4 lines below for connecting to another mysql networks (different container)
#networks:
#  default:
#    name: mysql
#    external: true
